# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  base_url: https://home.itdice.net
  use_x_forwarded_for: true
  trusted_proxies:
    127.0.0.1  #localhost
    
homeassistant:
  name: Home
  latitude: 37.376349
  longitude: 126.854290
  elevation: 50
  unit_system: metric
  currency: KRW
  time_zone: "Asia/Seoul"
  external_url: "https://home.itdice.net"
  internal_url: "http://192.168.0.43:8123"
  customize: !include customize.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

lovelace:
  
#  dashboards:
#    toget-home:
#      mode: yaml
#      title: Toget Home
#      icon: mdi:home-automation
#      show_in_sidebar: true
#      filename: togethome.yaml
